apiVersion: v1
kind: ConfigMap
metadata:
  name: agentinvest-config
  namespace: agentinvest
data:
  RESTATE_ADMIN_URL: "http://restate-service:9070"
  RESTATE_INGRESS_URL: "http://restate-service:8080"
  AGENTINVEST_ENDPOINT_PORT: "9090"
  AGENTINVEST_PY_ENDPOINT_PORT: "9091"
  AGENTINVEST_PY_DEPLOY_URL: "http://agentinvest-py-endpoint-service:9091"
